### Sign up
POST  http://127.0.0.1:4000/api/auth/signup 
Content-Type: application/x-www-form-urlencoded

&fullName=user user
&email=user@user.com
&password=123456
&confirmPassword=123456

### Log In
POST  http://127.0.0.1:4000/api/auth/login 
Content-Type: application/x-www-form-urlencoded

&email=admin@user.com
&password=1234567890

### User auth get info
GET http://127.0.0.1:4000/api/users/info
Content-Type: application/x-www-form-urlencoded
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwicm9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJmdWxsTmFtZSI6ImFkbWluIHVzZXIiLCJlbWFpbCI6ImFkbWluQHVzZXIuY29tIiwiY3JlYXRlZEF0IjoxNTk2MzIwMjkyLCJleHBpcmVkQXQiOjE1OTY0MDY2OTJ9.mFF1-PKPSiGJP_9VTClSjkK6dCbFnC_mufalzokbZbI

### User auth update data
PUT http://127.0.0.1:4000/api/users/update
Content-Type: application/x-www-form-urlencoded
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwicm9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJmdWxsTmFtZSI6ImFkbWluIHVzZXIiLCJlbWFpbCI6ImFkbWluQHVzZXIuY29tIiwiY3JlYXRlZEF0IjoxNTk2MzIwMjkyLCJleHBpcmVkQXQiOjE1OTY0MDY2OTJ9.mFF1-PKPSiGJP_9VTClSjkK6dCbFnC_mufalzokbZbI
&fullName= roxnny a barrios c
&email=admin@user.com

### User auth set request
PUT http://127.0.0.1:4000/api/users/request
Content-Type: application/x-www-form-urlencoded
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwicm9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJmdWxsTmFtZSI6ImFkbWluIHVzZXIiLCJlbWFpbCI6ImFkbWluQHVzZXIuY29tIiwiY3JlYXRlZEF0IjoxNTk2MzIwMjkyLCJleHBpcmVkQXQiOjE1OTY0MDY2OTJ9.mFF1-PKPSiGJP_9VTClSjkK6dCbFnC_mufalzokbZbI

### User auth get applicants
GET http://127.0.0.1:4000/api/users/applicants
Content-Type: application/x-www-form-urlencoded
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwicm9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJmdWxsTmFtZSI6ImFkbWluIHVzZXIiLCJlbWFpbCI6ImFkbWluQHVzZXIuY29tIiwiY3JlYXRlZEF0IjoxNTk2MzIwMjkyLCJleHBpcmVkQXQiOjE1OTY0MDY2OTJ9.mFF1-PKPSiGJP_9VTClSjkK6dCbFnC_mufalzokbZbI

### User auth admin create ticket
POST http://127.0.0.1:4000/api/tickets/create
Content-Type: application/x-www-form-urlencoded
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwicm9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJmdWxsTmFtZSI6ImFkbWluIHVzZXIiLCJlbWFpbCI6ImFkbWluQHVzZXIuY29tIiwiY3JlYXRlZEF0IjoxNTk2MzIwMjkyLCJleHBpcmVkQXQiOjE1OTY0MDY2OTJ9.mFF1-PKPSiGJP_9VTClSjkK6dCbFnC_mufalzokbZbI

&name= node
&description= node is awezome

### User auth admin update ticket
PUT  http://127.0.0.1:4000/api/tickets/update/2
Content-Type: application/x-www-form-urlencoded
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwicm9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJmdWxsTmFtZSI6ImFkbWluIHVzZXIiLCJlbWFpbCI6ImFkbWluQHVzZXIuY29tIiwiY3JlYXRlZEF0IjoxNTk2MzIwMjkyLCJleHBpcmVkQXQiOjE1OTY0MDY2OTJ9.mFF1-PKPSiGJP_9VTClSjkK6dCbFnC_mufalzokbZbI

&name= express
&description= express is awezome

### User auth admin delete ticket
DELETE  http://127.0.0.1:4000/api/tickets/delete/3
Content-Type: application/x-www-form-urlencoded
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwicm9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJmdWxsTmFtZSI6ImFkbWluIHVzZXIiLCJlbWFpbCI6ImFkbWluQHVzZXIuY29tIiwiY3JlYXRlZEF0IjoxNTk2MzIwMjkyLCJleHBpcmVkQXQiOjE1OTY0MDY2OTJ9.mFF1-PKPSiGJP_9VTClSjkK6dCbFnC_mufalzokbZbI

### User auth admin get all tickets
GET  http://127.0.0.1:4000/api/tickets/all/
Content-Type: application/x-www-form-urlencoded
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwicm9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJmdWxsTmFtZSI6ImFkbWluIHVzZXIiLCJlbWFpbCI6ImFkbWluQHVzZXIuY29tIiwiY3JlYXRlZEF0IjoxNTk2MzIwMjkyLCJleHBpcmVkQXQiOjE1OTY0MDY2OTJ9.mFF1-PKPSiGJP_9VTClSjkK6dCbFnC_mufalzokbZbI

### User auth admin get one ticket
GET  http://127.0.0.1:4000/api/tickets/one/1
Content-Type: application/x-www-form-urlencoded
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwicm9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJmdWxsTmFtZSI6ImFkbWluIHVzZXIiLCJlbWFpbCI6ImFkbWluQHVzZXIuY29tIiwiY3JlYXRlZEF0IjoxNTk2MzIwMjkyLCJleHBpcmVkQXQiOjE1OTY0MDY2OTJ9.mFF1-PKPSiGJP_9VTClSjkK6dCbFnC_mufalzokbZbI
