### Sign up
POST  http://127.0.0.1:4000/api/auth/signup 
Content-Type: application/x-www-form-urlencoded

&fullName=user user
&email=user@user.com
&password=123456
&confirmPassword=123456

### Log In
POST  http://127.0.0.1:4000/api/auth/login 
Content-Type: application/x-www-form-urlencoded

&email=admin@user.com
&password=1234567890

### User auth get info
GET http://127.0.0.1:4000/api/users/info
Content-Type: application/x-www-form-urlencoded
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwicm9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJmdWxsTmFtZSI6ImFkbWluIHVzZXIiLCJlbWFpbCI6ImFkbWluQHVzZXIuY29tIiwiY3JlYXRlZEF0IjoxNTk2MDUwMzM1LCJleHBpcmVkQXQiOjE1OTYxMzY3MzV9.lFeoRw1E64636rFmrxY7dC53vv_XAIXX7BXRGHF8Tro

### User auth update data
PUT http://127.0.0.1:4000/api/users/update
Content-Type: application/x-www-form-urlencoded
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwicm9sZUlkIjoxLCJyb2xlIjoiYWRtaW4iLCJmdWxsTmFtZSI6ImFkbWluIHVzZXIiLCJlbWFpbCI6ImFkbWluQHVzZXIuY29tIiwiY3JlYXRlZEF0IjoxNTk2MDUwMzM1LCJleHBpcmVkQXQiOjE1OTYxMzY3MzV9.lFeoRw1E64636rFmrxY7dC53vv_XAIXX7BXRGHF8Tro

&fullName= roxnny a barrios c
&email=admin@user.com